package com.bydcollector.collector.ui

import com.bydcollector.collector.data.local.CollectorEvent
import com.bydcollector.collector.maintenance.DbMaintenanceRuntimeStatus
import com.bydcollector.collector.system.RequiredAccessRow

data class DashboardState(
    val running: Boolean,
    val serviceRunning: Boolean,
    val mainPollingRunning: Boolean,
    val autoStartEnabled: Boolean,
    val pollingEnabled: Boolean,
    val activeSessionId: Long?,
    val lastSuccessAt: String?,
    val lastError: String?,
    val lastErrorAt: String?,
    val lastPollStatus: String?,
    val pollCount: Long,
    val valueRowCount: Long,
    val ecRowCount: Long,
    val lastEcImport: String?,
    val lastEcImportStatus: String?,
    val elapsedMs: Long?,
    val requestCount: Int?,
    val databasePath: String,
    val databaseSizeBytes: Long,
    val dbMaintenanceStatus: DbMaintenanceRuntimeStatus,
    val latestSoc: String?,
    val latestSpeed: String?,
    val latestCharging: String?,
    val logRecording: Boolean,
    val logDirectoryPath: String,
    val logPullCommand: String,
    val dbPullCommand: String,
    val debugPollingEnabled: Boolean,
    val debugPollingRunning: Boolean,
    val debugAutoStartEnabled: Boolean,
    val debugBatchSize: Int,
    val debugParameterCount: Int,
    val debugDatabasePath: String,
    val debugDatabaseSizeBytes: Long,
    val debugReadingCount: Long,
    val debugLastReadingAt: String?,
    val debugLastErrorAt: String?,
    val debugLastError: String?,
    val debugErrorCount: Long,
    val debugLastSessionId: Long?,
    val debugDbPullCommand: String,
    val keepWifiEnabled: Boolean,
    val keepMobileDataEnabled: Boolean,
    val keepBluetoothEnabled: Boolean,
    val recoverCollectorServiceEnabled: Boolean,
    val tailscaleActivationEnabled: Boolean,
    val keepAliveEnabled: Boolean,
    val keepAliveStatus: String,
    val keepAliveLogPullCommand: String,
    val mqttEnabled: Boolean,
    val mqttAutoStartEnabled: Boolean,
    val mqttHost: String,
    val mqttPort: Int,
    val mqttUsername: String,
    val mqttPasswordSet: Boolean,
    val mqttClientId: String,
    val mqttTopicPrefix: String,
    val mqttDiscoveryPrefix: String,
    val mqttEnabledCategories: Set<String>,
    val mqttStatus: String,
    val mqttLastError: String?,
    val mqttLastPublishedAt: String?,
    val mqttPendingCount: Long,
    val mqttRetryFailureCount: Int,
    val mqttNextRetryAt: String?,
    val mqttRetryLastFailureAt: String?,
    val mqttRetryLastSuccessAt: String?,
    val influxEnabled: Boolean,
    val influxAutoStartEnabled: Boolean,
    val haSharedCategoriesEnabled: Boolean,
    val influxHost: String,
    val influxPort: Int,
    val influxDatabase: String,
    val influxUsername: String,
    val influxPasswordSet: Boolean,
    val influxMeasurement: String,
    val influxEnabledCategories: Set<String>,
    val influxStatus: String,
    val influxMode: String?,
    val influxPendingRows: Long,
    val influxOldestPendingAt: String?,
    val influxNextRetryAt: String?,
    val influxLastSuccessAt: String?,
    val influxLastErrorAt: String?,
    val influxLastError: String?,
    val influxExportedRowsTotal: Long,
    val normalizedCurrentCount: Long,
    val normalizedHistoryCount: Long,
    val requiredAccessRows: List<RequiredAccessRow>,
    val directBridgeStatus: String?,
    val vehicleKpis: VehicleKpis,
    val recentEvents: List<CollectorEvent>
)

data class VehicleKpis(
    val socPercent: String = "-",
    val odometerKm: String = "-",
    val cabinTempC: String = "-",
    val sohPercent: String = "-",
    val batteryPowerCharging: Boolean = false,
    val batteryPowerKw: String = "-",
    val remainingRangeKm: String = "-",
    val batteryTempC: String = "-",
    val cellVoltageDeltaMv: String = "-"
)
