package com.bydcollector.collector.ui.compose

import com.bydcollector.collector.telegram.TelegramEventType
import com.bydcollector.collector.telegram.TelegramTemplateCatalog
import com.bydcollector.collector.telegram.TelegramTemplateLanguage

enum class AppTab {
    MAIN,
    ALL_PARAMETERS,
    TRIPS,
    HA,
    TELEGRAM,
    STORAGE,
    EXTRA
}

enum class UiLanguage {
    UK,
    EN;

    val code: String get() = if (this == EN) "en" else "uk"

    companion object {
        fun fromCode(code: String): UiLanguage = if (code.trim().equals("en", ignoreCase = true)) EN else UK
    }
}

enum class StatusKind {
    OK,
    WARNING,
    WAITING,
    ERROR
}

data class TabText(
    val title: String,
    val subtitle: String
)

data class TelegramMessageStrings(
    val title: String,
    val defaultTemplate: String
)

data class TelegramStrings(
    val tab: String,
    val subtitle: String,
    val connection: String,
    val enable: String,
    val botToken: String,
    val chatId: String,
    val notTested: String,
    val testing: String,
    val connected: String,
    val storageError: String,
    val failed: String,
    val messageTemplate: String,
    val messagePlaceholder: String,
    val insertVariable: String,
    val clearBotToken: String,
    val chargeStep: String,
    val low12vThreshold: String,
    val telemetryDelay: String,
    val tripDelay: String,
    val locationSettings: String,
    val locationMaster: String,
    val googleNavigator: String,
    val wazeNavigator: String,
    val appleNavigator: String,
    val osmNavigator: String,
    val locationClose: String,
    val locationStatusNo: String,
    val locationStatusYes: String,
    val minuteUnit: String,
    val secondUnit: String,
    val messages: Map<TelegramMessageType, TelegramMessageStrings>,
    val variableDescriptions: Map<String, String>
)

data class UiStrings(
    val appSubtitle: String,
    val topBarSubtitle: String,
    val collection: String,
    val adb: String,
    val permissions: String,
    val success: String,
    val error: String,
    val uk: String,
    val en: String,
    val dark: String,
    val light: String,
    val start: String,
    val stop: String,
    val testConnection: String,
    val showSecret: String,
    val hideSecret: String,
    val autoStart: String,
    val controls: String,
    val telegram: TelegramStrings,
    val mainTab: String,
    val allTab: String,
    val haTab: String,
    val tripsTab: String,
    val storageTab: String,
    val extraTab: String,
    val mainSubtitle: String,
    val allSubtitle: String,
    val haSubtitle: String,
    val tripsSubtitle: String,
    val storageSubtitle: String,
    val extraSubtitle: String,
    val dataCollection: String,
    val archiveDatabase: String,
    val archiveDebugDatabase: String,
    val grantAdb: String,
    val backgroundWork: String,
    val backgroundSetupTitle: String,
    val backgroundSetupMessage: String,
    val backgroundSetupBody: String,
    val backgroundSetupOpen: String,
    val backgroundSetupDismiss: String,
    val status: String,
    val activeChannels: String,
    val database: String,
    val activeDatabase: String,
    val activeDatabaseSizeTemplate: String,
    val mainStorageCutoverDeferred: String,
    val mainStorageCutoverErrorTemplate: String,
    val debugStorageCutoverErrorTemplate: String,
    val archiveStorage: String,
    val archiveStorageLimit: String,
    val archiveStorageLimitHint: String,
    val archiveRoot: String,
    val archiveCount: String,
    val archiveStatusRaw: String,
    val archiveStatusZip: String,
    val archiveStatusTmp: String,
    val archiveStorageEmpty: String,
    val archiveStorageScanning: String,
    val shareSelectedArchives: String,
    val archiveShareFailed: String,
    val archivePreflightFailed: String,
    val archiveCalculating: String,
    val archiveSortNewestFirst: String,
    val archiveSortOldestFirst: String,
    val archiveCountShortTemplate: String,
    val deleteSelected: String,
    val selectedArchivesTemplate: String,
    val deleteArchivesQuestion: String,
    val deletingArchive: String,
    val size: String,
    val megabytesUnit: String,
    val gigabytesUnit: String,
    val rows: String,
    val points: String,
    val queued: String,
    val exported: String,
    val currentVehicleState: String,
    val kpiSoc: String,
    val kpiOdometer: String,
    val kpiCabinTemp: String,
    val kpiSoh: String,
    val kpiCharging: String,
    val kpiDischarging: String,
    val kpiRange: String,
    val kpiBatteryTemp: String,
    val kpiCellDelta: String,
    val parametersPerCycle: String,
    val battery: String,
    val motion: String,
    val body: String,
    val climate: String,
    val safety: String,
    val driverAssist: String,
    val sharedCategories: String,
    val reExport: String,
    val reExportHint: String,
    val host: String,
    val port: String,
    val username: String,
    val password: String,
    val databaseField: String,
    val measurement: String,
    val clientId: String,
    val topicPrefix: String,
    val discoveryPrefix: String,
    val mqttCategories: String,
    val influxCategories: String,
    val location: String,
    val sendLocation: String,
    val routeColors: String,
    val tripList: String,
    val speed: String,
    val consumption: String,
    val green: String,
    val yellow: String,
    val red: String,
    val startEnd: String,
    val duration: String,
    val distance: String,
    val used: String,
    val averageConsumption: String,
    val route: String,
    val noTrips: String,
    val tripRoute: String,
    val colorBySpeed: String,
    val colorByConsumption: String,
    val tripStart: String,
    val tripFinish: String,
    val tripNoData: String,
    val keepWifi: String,
    val keepMobile: String,
    val keepBluetooth: String,
    val restoreCollector: String,
    val activateTailscale: String,
    val activateTailscaleDescription: String,
    val keepAlive: String,
    val appRuntime: String,
    val shutdown: String,
    val shutdownDescription: String,
    val network: String,
    val bluetooth: String,
    val collector: String,
    val updates: String,
    val checkUpdates: String,
    val checkUpdatesDescription: String,
    val checkingForUpdate: String,
    val downloadingUpdate: String,
    val latestVersion: String,
    val currentVersion: String,
    val availableVersion: String,
    val update: String,
    val close: String,
    val updateError: String,
    val updateNetworkUnavailable: String,
    val updateDownloadFailed: String,
    val updateVerificationFailed: String,
    val updateInstallFailed: String,
    val updateGenericError: String,
    val startLogcat: String,
    val stopLogcat: String,
    val mainPolling: String,
    val allParameters: String,
    val mqttPublish: String,
    val influxExport: String,
    val lastSuccess: String,
    val lastError: String,
    val batch: String,
    val waiting: String,
    val running: String,
    val exporting: String,
    val successful: String,
    val missing: String,
    val ok: String,
    val cancel: String,
    val idle: String,
    val stopped: String,
    val starting: String,
    val messages: String,
    val yes: String,
    val no: String,
    val step: String,
    val dbMaintenanceStopWarning: String,
    val dbMaintenanceDebugStopWarning: String,
    val dbMaintenancePendingTemplate: String,
    val dbMaintenanceTelegramDeferredWarning: String,
    val dbMaintenanceArchivePendingWarning: String,
    val dbMaintenanceConfirmTemplate: String,
    val operationCannotBeStopped: String,
    val interruptionDataLossRisk: String,
    val dbMaintenanceComplete: String,
    val dbMaintenanceFailed: String,
    val dbMaintenanceInterrupted: String,
    val dbMaintenanceAlreadyRunning: String,
    val dbMaintenanceCancelled: String,
    val dbMaintenanceGenericError: String,
    val dbMaintenanceArchivePath: String
)

private val telegramUk = TelegramStrings(
    tab = "Telegram",
    subtitle = "Окремі події та власні шаблони повідомлень",
    connection = "Підключення",
    enable = "Увімкнути Telegram",
    botToken = "Bot token",
    chatId = "Chat ID",
    notTested = "не перевірено",
    testing = "перевіряємо",
    connected = "зв'язок працює",
    storageError = "помилка сховища",
    failed = "помилка зв'язку",
    messageTemplate = "Шаблон повідомлення",
    messagePlaceholder = "Текст повідомлення",
    insertVariable = "Вставити змінну",
    clearBotToken = "Очистити Bot token",
    chargeStep = "Крок заряду",
    low12vThreshold = "Поріг напруги",
    telemetryDelay = "Затримка сповіщення",
    tripDelay = "Завершити після P",
    locationSettings = "Налаштування локації",
    locationMaster = "Надсилати локацію",
    googleNavigator = "Google",
    wazeNavigator = "Waze",
    appleNavigator = "Apple",
    osmNavigator = "OSM",
    locationClose = "Готово",
    locationStatusNo = "ні",
    locationStatusYes = "так, %d посилань",
    minuteUnit = "хв",
    secondUnit = "с",
    messages = mapOf(
        TelegramMessageType.CHARGING_STARTED to TelegramMessageStrings(
            "Заряджання розпочато",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_STARTED, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.CHARGING_PROGRESS to TelegramMessageStrings(
            "Прогрес заряджання",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_PROGRESS, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.CHARGED_TO_100 to TelegramMessageStrings(
            "Заряджено до 100%",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGED_TO_100, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.CHARGING_STOPPED to TelegramMessageStrings(
            "Заряджання зупинено",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_STOPPED, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.CHARGE_GUN_CONNECTED to TelegramMessageStrings(
            "Зарядний кабель підключено",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGE_GUN_CONNECTED, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.CHARGE_GUN_DISCONNECTED to TelegramMessageStrings(
            "Зарядний кабель відключено",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGE_GUN_DISCONNECTED, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.LOW_12V_VOLTAGE to TelegramMessageStrings(
            "Низька напруга 12V",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.LOW_12V_VOLTAGE, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.TELEMETRY_UNAVAILABLE to TelegramMessageStrings(
            "Телеметрія недоступна",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.TELEMETRY_UNAVAILABLE, TelegramTemplateLanguage.UK)
        ),
        TelegramMessageType.TRIP_SUMMARY to TelegramMessageStrings(
            "Підсумок поїздки",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.TRIP_SUMMARY, TelegramTemplateLanguage.UK)
        )
    ),
    variableDescriptions = mapOf(
        "soc" to "Поточний заряд батареї, %",
        "battery_power_kw" to "Поточна потужність заряджання, кВт",
        "charge_step_added_percent" to "Доданий заряд за поточний крок, %",
        "charge_step_added_kwh" to "Додана енергія за поточний крок, кВт·год",
        "charge_added_percent" to "Доданий заряд за всю сесію, %",
        "charge_added_kwh" to "Додана енергія за всю сесію, кВт·год",
        "remaining_energy_kwh" to "Залишок енергії, кВт·год",
        "range_km" to "Розрахунковий запас ходу, км",
        "charge_duration" to "Тривалість заряджання",
        "charge_start_time" to "Час початку заряджання, HH:mm",
        "charge_end_time" to "Час завершення заряджання, HH:mm",
        "charge_duration_hhmm" to "Тривалість заряджання, загальні години HH:mm",
        "time" to "Час події",
        "battery_12v" to "Напруга 12V батареї, В",
        "last_data_time" to "Час останніх валідних даних",
        "error" to "Короткий опис помилки",
        "trip_distance_km" to "Відстань поїздки, км",
        "trip_energy_kwh" to "Енергія поїздки, кВт·год",
        "trip_duration" to "Тривалість поїздки",
        "soc_start" to "SOC на початку поїздки, %",
        "soc_end" to "SOC наприкінці поїздки, %",
        "total_distance_km" to "Загальна відстань, км",
        "total_energy_kwh" to "Загальна витрата енергії, кВт·год",
        "total_duration" to "Загальна тривалість поїздок"
    )
)

private val telegramEn = TelegramStrings(
    tab = "Telegram",
    subtitle = "Independent events and custom message templates",
    connection = "Connection",
    enable = "Enable Telegram",
    botToken = "Bot token",
    chatId = "Chat ID",
    notTested = "not tested",
    testing = "testing",
    connected = "connected",
    storageError = "storage error",
    failed = "connection failed",
    messageTemplate = "Message template",
    messagePlaceholder = "Message text",
    insertVariable = "Insert variable",
    clearBotToken = "Clear Bot token",
    chargeStep = "Charge step",
    low12vThreshold = "Voltage threshold",
    telemetryDelay = "Notification delay",
    tripDelay = "Finish after P",
    locationSettings = "Location settings",
    locationMaster = "Send location",
    googleNavigator = "Google",
    wazeNavigator = "Waze",
    appleNavigator = "Apple",
    osmNavigator = "OSM",
    locationClose = "Done",
    locationStatusNo = "no",
    locationStatusYes = "yes, %d links",
    minuteUnit = "min",
    secondUnit = "sec",
    messages = mapOf(
        TelegramMessageType.CHARGING_STARTED to TelegramMessageStrings(
            "Charging started",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_STARTED, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.CHARGING_PROGRESS to TelegramMessageStrings(
            "Charging progress",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_PROGRESS, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.CHARGED_TO_100 to TelegramMessageStrings(
            "Charged to 100%",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGED_TO_100, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.CHARGING_STOPPED to TelegramMessageStrings(
            "Charging stopped",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGING_STOPPED, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.CHARGE_GUN_CONNECTED to TelegramMessageStrings(
            "Charge gun connected",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGE_GUN_CONNECTED, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.CHARGE_GUN_DISCONNECTED to TelegramMessageStrings(
            "Charge gun disconnected",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.CHARGE_GUN_DISCONNECTED, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.LOW_12V_VOLTAGE to TelegramMessageStrings(
            "Low 12V voltage",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.LOW_12V_VOLTAGE, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.TELEMETRY_UNAVAILABLE to TelegramMessageStrings(
            "Telemetry unavailable",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.TELEMETRY_UNAVAILABLE, TelegramTemplateLanguage.EN)
        ),
        TelegramMessageType.TRIP_SUMMARY to TelegramMessageStrings(
            "Trip summary",
            TelegramTemplateCatalog.defaultTemplate(TelegramEventType.TRIP_SUMMARY, TelegramTemplateLanguage.EN)
        )
    ),
    variableDescriptions = mapOf(
        "soc" to "Current battery charge, %",
        "battery_power_kw" to "Current charging power, kW",
        "charge_step_added_percent" to "Charge added during the current step, %",
        "charge_step_added_kwh" to "Energy added during the current step, kWh",
        "charge_added_percent" to "Charge added during the whole session, %",
        "charge_added_kwh" to "Energy added during the whole session, kWh",
        "remaining_energy_kwh" to "Remaining energy, kWh",
        "range_km" to "Estimated range, km",
        "charge_duration" to "Charging duration",
        "charge_start_time" to "Charging start time, HH:mm",
        "charge_end_time" to "Charging end time, HH:mm",
        "charge_duration_hhmm" to "Charging duration, total-hours HH:mm",
        "time" to "Event time",
        "battery_12v" to "12V battery voltage, V",
        "last_data_time" to "Last valid data time",
        "error" to "Short error description",
        "trip_distance_km" to "Trip distance, km",
        "trip_energy_kwh" to "Trip energy, kWh",
        "trip_duration" to "Trip duration",
        "soc_start" to "SOC at trip start, %",
        "soc_end" to "SOC at trip end, %",
        "total_distance_km" to "Total distance, km",
        "total_energy_kwh" to "Total energy used, kWh",
        "total_duration" to "Total trip duration"
    )
)

private fun buildStrings(language: UiLanguage): UiStrings {
    return when (language) {
        UiLanguage.UK -> UiStrings(
            appSubtitle = "Прямий збір телеметрії • Sea Lion 07 EV",
            topBarSubtitle = "Збирання телеметрії авто",
            collection = "Збір",
            adb = "ADB",
            permissions = "Права",
            success = "Успіх",
            error = "Помилка",
            uk = "Укр",
            en = "Англ",
            dark = "Темна",
            light = "Світла",
            start = "Старт",
            stop = "Стоп",
            testConnection = "Тест зв'язку",
            showSecret = "Показати секрет",
            hideSecret = "Приховати секрет",
            autoStart = "Автоматичний запуск",
            controls = "Керування",
            telegram = telegramUk,
            mainTab = "Головна",
            allTab = "Всі дані",
            haTab = "HA інтеграція",
            tripsTab = "Поїздки",
            storageTab = "Сховище",
            extraTab = "Опції",
            mainSubtitle = "Керування основним збором, швидка діагностика",
            allSubtitle = "Round-robin збір додаткових параметрів.",
            haSubtitle = "MQTT для live state, InfluxDB для історії та Grafana. Канали незалежні.",
            tripsSubtitle = "Історія поїздок і маршрути OpenStreetMap.",
            storageSubtitle = "Архіви бази та ліміт зберігання",
            extraSubtitle = "Окремі налаштування (у стані тестування)",
            dataCollection = "Збір даних",
            archiveDatabase = "Архівація бази",
            archiveDebugDatabase = "Архівація тестової бази",
            grantAdb = "Видати ADB",
            backgroundWork = "Робота у фоні",
            backgroundSetupTitle = "Робота у фоні",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Відкрийте DiLink settings і вимкніть примусове закриття застосунку у фоні.",
            backgroundSetupOpen = "Відкрити",
            backgroundSetupDismiss = "Зрозуміло",
            status = "Статус",
            activeChannels = "Активні канали",
            database = "База",
            activeDatabase = "Поточні бази",
            activeDatabaseSizeTemplate = "%s: основна %s + тестова %s",
            mainStorageCutoverDeferred = "Main DB v2: перехід відкладено до ручної архівації.",
            mainStorageCutoverErrorTemplate = "Main DB v2: %s",
            debugStorageCutoverErrorTemplate = "Round-robin DB v2: %s",
            archiveStorage = "Архіви",
            archiveStorageLimit = "Ліміт архівів, ГБ",
            archiveStorageLimitHint = "Автоматично видаляти найстаріші архіви після перевищення ліміту",
            archiveRoot = "Тека архівів",
            archiveCount = "Архівів",
            archiveStatusRaw = "raw",
            archiveStatusZip = "zip",
            archiveStatusTmp = "tmp",
            archiveStorageEmpty = "Архівів немає",
            archiveStorageScanning = "Сховище сканується...",
            shareSelectedArchives = "Поділитися вибраними архівами",
            archiveShareFailed = "Не вдалося поділитися вибраними архівами",
            archivePreflightFailed = "Не вдалося перевірити стан бази",
            archiveCalculating = "обчислюємо...",
            archiveSortNewestFirst = "Нові спочатку",
            archiveSortOldestFirst = "Старі спочатку",
            archiveCountShortTemplate = "(%d арх.)",
            deleteSelected = "Видалити вибране",
            selectedArchivesTemplate = "Вибрано: %d",
            deleteArchivesQuestion = "Видалити вибрані архіви?",
            deletingArchive = "Видаляємо архів...",
            size = "Розмір",
            megabytesUnit = "МБ",
            gigabytesUnit = "ГБ",
            rows = "Рядів",
            points = "точок",
            queued = "У черзі",
            exported = "Експортовано",
            currentVehicleState = "Поточний стан авто",
            kpiSoc = "SOC",
            kpiOdometer = "Пробіг",
            kpiCabinTemp = "Темп. салону",
            kpiSoh = "SOH",
            kpiCharging = "Заряджання",
            kpiDischarging = "Розряджання",
            kpiRange = "Запас ходу",
            kpiBatteryTemp = "Темп. батареї",
            kpiCellDelta = "Δ напруги комірки",
            parametersPerCycle = "Параметрів за цикл",
            battery = "Батарея",
            motion = "Рух",
            body = "Кузов",
            climate = "Клімат",
            safety = "Безпека",
            driverAssist = "Асистенти",
            sharedCategories = "Спільні категорії MQTT/InfluxDB",
            reExport = "Ре-експорт",
            reExportHint = "Експорт історії тільки нових категорій",
            host = "Хост",
            port = "Порт",
            username = "Користувач",
            password = "Пароль",
            databaseField = "База даних",
            measurement = "Вимірювання",
            clientId = "ID клієнта",
            topicPrefix = "Префікс топіків",
            discoveryPrefix = "Префікс discovery",
            mqttCategories = "Категорії MQTT",
            influxCategories = "Категорії InfluxDB",
            location = "Локація",
            sendLocation = "Надсилати локацію",
            routeColors = "Кольори маршруту",
            tripList = "Перелік поїздок",
            speed = "Швидкість, км/год",
            consumption = "Витрата, кВт·год/100 км",
            green = "зелений",
            yellow = "жовтий",
            red = "червоний",
            startEnd = "Початок -> Кінець",
            duration = "Час",
            distance = "Відстань",
            used = "Витрачено",
            averageConsumption = "Середня витрата",
            route = "Маршрут",
            noTrips = "Поїздок ще немає",
            tripRoute = "Маршрут поїздки",
            colorBySpeed = "Колір за швидкістю",
            colorByConsumption = "Колір за витратою",
            tripStart = "Початок",
            tripFinish = "Кінець",
            tripNoData = "Відсутні дані",
            keepWifi = "Утримувати Wi-Fi",
            keepMobile = "Утримувати моб. зв'язок",
            keepBluetooth = "Утримувати Bluetooth",
            restoreCollector = "Відновлювати сервіс",
            activateTailscale = "Активувати Tailscale",
            activateTailscaleDescription = "Перевіряти наявність Tailscale та активувати VPN",
            keepAlive = "Підтримка роботи",
            appRuntime = "Робота застосунку",
            shutdown = "Виключити",
            shutdownDescription = "Завершити роботу застосунку до наступного відкриття",
            network = "Мережа",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Оновлення",
            checkUpdates = "Перевірити оновлення",
            checkUpdatesDescription = "Перевіряти наявність нової версії та пропонувати оновитись",
            checkingForUpdate = "Перевіряємо оновлення...",
            downloadingUpdate = "Завантажуємо оновлення...",
            latestVersion = "Це остання версія застосунку",
            currentVersion = "Поточна версія:",
            availableVersion = "Доступна версія:",
            update = "Оновити",
            close = "Закрити",
            updateError = "Помилка перевірки оновлення",
            updateNetworkUnavailable = "Немає з'єднання. Перевірте мережу або VPN.",
            updateDownloadFailed = "Не вдалося завантажити оновлення.",
            updateVerificationFailed = "Файл оновлення не пройшов перевірку.",
            updateInstallFailed = "Не вдалося відкрити встановлення оновлення.",
            updateGenericError = "Не вдалося перевірити або встановити оновлення.",
            startLogcat = "Старт logcat",
            stopLogcat = "Стоп logcat",
            mainPolling = "Збір основних даних",
            allParameters = "Всі дані",
            mqttPublish = "MQTT публікація",
            influxExport = "InfluxDB експорт",
            lastSuccess = "Останній успіх",
            lastError = "Остання помилка",
            batch = "Батч",
            waiting = "очікування",
            running = "працює",
            exporting = "експортує",
            successful = "успішно",
            missing = "відсутні",
            ok = "OK",
            cancel = "Скасувати",
            idle = "очікування",
            stopped = "зупинено",
            starting = "запуск",
            messages = "повідомлень",
            yes = "Так",
            no = "Ні",
            step = "Крок",
            dbMaintenanceStopWarning = "Буде тимчасово зупинено основний збір, всі дані, MQTT та InfluxDB.",
            dbMaintenanceDebugStopWarning = "Буде тимчасово зупинено лише round-robin збір. Основний збір, MQTT та InfluxDB продовжать працювати.",
            dbMaintenancePendingTemplate = "У черзі: Telegram %d, MQTT %d, InfluxDB %d.",
            dbMaintenanceTelegramDeferredWarning = "У Telegram є незавершений стан подій або приглушення повторів.",
            dbMaintenanceArchivePendingWarning = "Архівація з активною чергою може залишити частину даних тільки в архіві.",
            dbMaintenanceConfirmTemplate = "Виконати операцію %s?",
            operationCannotBeStopped = "Після початку зупинити операцію із застосунку неможливо.",
            interruptionDataLossRisk = "Переривання процесу створює ризик втрати даних!",
            dbMaintenanceComplete = "Операцію завершено",
            dbMaintenanceFailed = "Операцію не виконано",
            dbMaintenanceInterrupted = "Операцію перервано до завершення.",
            dbMaintenanceAlreadyRunning = "Операція вже виконується.",
            dbMaintenanceCancelled = "Операцію скасовано.",
            dbMaintenanceGenericError = "Операцію не виконано. Деталі записані в логах.",
            dbMaintenanceArchivePath = "Архів:"
        )

        UiLanguage.EN -> UiStrings(
            appSubtitle = "Direct telemetry collection • Sea Lion 07 EV",
            topBarSubtitle = "Auto telemetry collection",
            collection = "Collection",
            adb = "ADB",
            permissions = "Permissions",
            success = "Success",
            error = "Error",
            uk = "UA",
            en = "ENG",
            dark = "Dark",
            light = "Light",
            start = "Start",
            stop = "Stop",
            testConnection = "Test connection",
            showSecret = "Show secret",
            hideSecret = "Hide secret",
            autoStart = "Automatic start",
            controls = "Controls",
            telegram = telegramEn,
            mainTab = "Main",
            allTab = "All data",
            haTab = "HA integration",
            tripsTab = "Trips",
            storageTab = "Storage",
            extraTab = "Options",
            mainSubtitle = "Main collection controls, quick diagnostics",
            allSubtitle = "Round-robin collection of additional parameters.",
            haSubtitle = "MQTT for live state, InfluxDB for history and Grafana. Channels are independent.",
            tripsSubtitle = "Trip history and OpenStreetMap routes.",
            storageSubtitle = "Database archives and storage limit",
            extraSubtitle = "Separate settings (testing)",
            dataCollection = "Data collection",
            archiveDatabase = "Archive database",
            archiveDebugDatabase = "Archive test database",
            grantAdb = "Grant ADB",
            backgroundWork = "Background apps",
            backgroundSetupTitle = "Background work",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Open DiLink settings and disable forced background app shutdown for this app.",
            backgroundSetupOpen = "Open settings",
            backgroundSetupDismiss = "Got it",
            status = "Status",
            activeChannels = "Active channels",
            database = "Database",
            activeDatabase = "Active databases",
            activeDatabaseSizeTemplate = "%s: main %s + test %s",
            mainStorageCutoverDeferred = "Main DB v2: transition deferred until manual archive.",
            mainStorageCutoverErrorTemplate = "Main DB v2: %s",
            debugStorageCutoverErrorTemplate = "Round-robin DB v2: %s",
            archiveStorage = "Archives",
            archiveStorageLimit = "Archive limit, GB",
            archiveStorageLimitHint = "Delete oldest archives automatically after the limit is exceeded",
            archiveRoot = "Archive folder",
            archiveCount = "Archives",
            archiveStatusRaw = "raw",
            archiveStatusZip = "zip",
            archiveStatusTmp = "tmp",
            archiveStorageEmpty = "No archives",
            archiveStorageScanning = "Scanning storage...",
            shareSelectedArchives = "Share selected archives",
            archiveShareFailed = "Could not share selected archives",
            archivePreflightFailed = "Could not check database status",
            archiveCalculating = "calculating...",
            archiveSortNewestFirst = "Newest first",
            archiveSortOldestFirst = "Oldest first",
            archiveCountShortTemplate = "(%d arch.)",
            deleteSelected = "Delete selected",
            selectedArchivesTemplate = "Selected: %d",
            deleteArchivesQuestion = "Delete selected archives?",
            deletingArchive = "Deleting archive...",
            size = "Size",
            megabytesUnit = "MB",
            gigabytesUnit = "GB",
            rows = "Rows",
            points = "points",
            queued = "Queued",
            exported = "Exported",
            currentVehicleState = "Current vehicle state",
            kpiSoc = "SOC",
            kpiOdometer = "Odometer",
            kpiCabinTemp = "Cabin temp",
            kpiSoh = "SOH",
            kpiCharging = "Charging",
            kpiDischarging = "Discharging",
            kpiRange = "Range",
            kpiBatteryTemp = "Battery temp",
            kpiCellDelta = "Cell voltage Δ",
            parametersPerCycle = "Parameters per cycle",
            battery = "Battery",
            motion = "Motion",
            body = "Body",
            climate = "Climate",
            safety = "Safety",
            driverAssist = "Driver assist",
            sharedCategories = "Shared MQTT/InfluxDB categories",
            reExport = "Re-export",
            reExportHint = "Export history for new categories only",
            host = "Host",
            port = "Port",
            username = "Username",
            password = "Password",
            databaseField = "Database",
            measurement = "Measurement",
            clientId = "Client ID",
            topicPrefix = "Topic prefix",
            discoveryPrefix = "Discovery prefix",
            mqttCategories = "MQTT categories",
            influxCategories = "InfluxDB categories",
            location = "Location",
            sendLocation = "Send location",
            routeColors = "Route colors",
            tripList = "Trip list",
            speed = "Speed, km/h",
            consumption = "Consumption, kWh/100 km",
            green = "green",
            yellow = "yellow",
            red = "red",
            startEnd = "Start -> End",
            duration = "Time",
            distance = "Distance",
            used = "Used",
            averageConsumption = "Avg. consumption",
            route = "Route",
            noTrips = "No trips yet",
            tripRoute = "Trip route",
            colorBySpeed = "Color by speed",
            colorByConsumption = "Color by consumption",
            tripStart = "Start",
            tripFinish = "Finish",
            tripNoData = "No data",
            keepWifi = "Keep Wi-Fi",
            keepMobile = "Keep mobile data",
            keepBluetooth = "Keep Bluetooth",
            restoreCollector = "Restore service",
            activateTailscale = "Activate Tailscale",
            activateTailscaleDescription = "Check for Tailscale and activate VPN",
            keepAlive = "Keep alive",
            appRuntime = "App runtime",
            shutdown = "Shutdown",
            shutdownDescription = "Stop the app until it is opened again",
            network = "Network",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Updates",
            checkUpdates = "Check for updates",
            checkUpdatesDescription = "Check for new version and offer updating",
            checkingForUpdate = "Checking for update...",
            downloadingUpdate = "Downloading update...",
            latestVersion = "This is the latest app version",
            currentVersion = "Current version:",
            availableVersion = "Available version:",
            update = "Update",
            close = "Close",
            updateError = "Update check error",
            updateNetworkUnavailable = "No connection. Check the network or VPN.",
            updateDownloadFailed = "Could not download the update.",
            updateVerificationFailed = "The update file failed verification.",
            updateInstallFailed = "Could not open update installation.",
            updateGenericError = "Could not check or install the update.",
            startLogcat = "Start logcat",
            stopLogcat = "Stop logcat",
            mainPolling = "Main polling",
            allParameters = "All data",
            mqttPublish = "MQTT publish",
            influxExport = "InfluxDB export",
            lastSuccess = "Last success",
            lastError = "Last error",
            batch = "Batch",
            waiting = "waiting",
            running = "running",
            exporting = "exporting",
            successful = "success",
            missing = "missing",
            ok = "OK",
            cancel = "Cancel",
            idle = "idle",
            stopped = "stopped",
            starting = "starting",
            messages = "messages",
            yes = "Yes",
            no = "No",
            step = "Step",
            dbMaintenanceStopWarning = "Main collection, all data, MQTT, and InfluxDB will be temporarily stopped.",
            dbMaintenanceDebugStopWarning = "Only round-robin collection will be paused. Main collection, MQTT, and InfluxDB will keep running.",
            dbMaintenancePendingTemplate = "Queued: Telegram %d, MQTT %d, InfluxDB %d.",
            dbMaintenanceTelegramDeferredWarning = "Telegram has unfinished event or repeat-suppression state.",
            dbMaintenanceArchivePendingWarning = "Archiving with an active queue can leave some data only inside the archive.",
            dbMaintenanceConfirmTemplate = "Run operation %s?",
            operationCannotBeStopped = "After the operation starts, it cannot be stopped from the app.",
            interruptionDataLossRisk = "Process interruption creates data corruption risk!",
            dbMaintenanceComplete = "Operation complete",
            dbMaintenanceFailed = "Operation failed",
            dbMaintenanceInterrupted = "The operation was interrupted before completion.",
            dbMaintenanceAlreadyRunning = "The operation is already running.",
            dbMaintenanceCancelled = "The operation was cancelled.",
            dbMaintenanceGenericError = "The operation failed. Details were written to logs.",
            dbMaintenanceArchivePath = "Archive:"
        )
    }
}

private val uiStringsUk = buildStrings(UiLanguage.UK)
private val uiStringsEn = buildStrings(UiLanguage.EN)

fun strings(language: UiLanguage): UiStrings = when (language) {
    UiLanguage.UK -> uiStringsUk
    UiLanguage.EN -> uiStringsEn
}
