package com.bydcollector.collector.ui.compose

enum class AppTab {
    MAIN,
    ALL_PARAMETERS,
    HA,
    STORAGE,
    EXTRA,
    LOGS
}

enum class UiLanguage {
    UK,
    EN
}

enum class StatusKind {
    OK,
    WARNING,
    WAITING,
    ERROR
}

data class TabText(
    val title: String,
    val subtitle: String
)

data class UiStrings(
    val appSubtitle: String,
    val topBarSubtitle: String,
    val collection: String,
    val adb: String,
    val permissions: String,
    val success: String,
    val error: String,
    val uk: String,
    val en: String,
    val dark: String,
    val light: String,
    val start: String,
    val stop: String,
    val testConnection: String,
    val autoStart: String,
    val controls: String,
    val mainTab: String,
    val allTab: String,
    val haTab: String,
    val storageTab: String,
    val extraTab: String,
    val logsTab: String,
    val mainSubtitle: String,
    val allSubtitle: String,
    val haSubtitle: String,
    val storageSubtitle: String,
    val extraSubtitle: String,
    val logsSubtitle: String,
    val dataCollection: String,
    val archiveDatabase: String,
    val grantAdb: String,
    val backgroundWork: String,
    val backgroundSetupTitle: String,
    val backgroundSetupMessage: String,
    val backgroundSetupBody: String,
    val backgroundSetupOpen: String,
    val backgroundSetupDismiss: String,
    val status: String,
    val activeChannels: String,
    val database: String,
    val activeDatabase: String,
    val archiveStorage: String,
    val archiveStorageLimit: String,
    val archiveStorageLimitHint: String,
    val archiveRoot: String,
    val archiveCount: String,
    val archiveStatusRaw: String,
    val archiveStatusZip: String,
    val archiveStatusTmp: String,
    val archiveStorageEmpty: String,
    val archiveStorageRefresh: String,
    val archiveCalculating: String,
    val archiveSortNewestFirst: String,
    val archiveSortOldestFirst: String,
    val archiveCountShortTemplate: String,
    val deleteSelected: String,
    val selectedArchivesTemplate: String,
    val deleteArchivesQuestion: String,
    val deletingArchive: String,
    val size: String,
    val megabytesUnit: String,
    val gigabytesUnit: String,
    val rows: String,
    val points: String,
    val queued: String,
    val exported: String,
    val currentVehicleState: String,
    val kpiSoc: String,
    val kpiOdometer: String,
    val kpiCabinTemp: String,
    val kpiSoh: String,
    val kpiCharging: String,
    val kpiDischarging: String,
    val kpiRange: String,
    val kpiBatteryTemp: String,
    val kpiCellDelta: String,
    val parametersPerCycle: String,
    val battery: String,
    val motion: String,
    val body: String,
    val climate: String,
    val safety: String,
    val driverAssist: String,
    val sharedCategories: String,
    val reExport: String,
    val reExportHint: String,
    val host: String,
    val port: String,
    val username: String,
    val password: String,
    val databaseField: String,
    val measurement: String,
    val clientId: String,
    val topicPrefix: String,
    val discoveryPrefix: String,
    val mqttCategories: String,
    val influxCategories: String,
    val keepWifi: String,
    val keepMobile: String,
    val keepBluetooth: String,
    val restoreCollector: String,
    val activateTailscale: String,
    val activateTailscaleDescription: String,
    val keepAlive: String,
    val appRuntime: String,
    val shutdown: String,
    val shutdownDescription: String,
    val network: String,
    val bluetooth: String,
    val collector: String,
    val updates: String,
    val checkUpdates: String,
    val checkUpdatesDescription: String,
    val checkingForUpdate: String,
    val downloadingUpdate: String,
    val latestVersion: String,
    val currentVersion: String,
    val availableVersion: String,
    val update: String,
    val close: String,
    val updateError: String,
    val updateNetworkUnavailable: String,
    val updateDownloadFailed: String,
    val updateVerificationFailed: String,
    val updateInstallFailed: String,
    val updateGenericError: String,
    val startJournal: String,
    val stopJournal: String,
    val startLogcat: String,
    val stopLogcat: String,
    val mainPolling: String,
    val allParameters: String,
    val mqttPublish: String,
    val influxExport: String,
    val lastSuccess: String,
    val lastError: String,
    val sessionErrors: String,
    val batch: String,
    val waiting: String,
    val running: String,
    val exporting: String,
    val successful: String,
    val missing: String,
    val ok: String,
    val cancel: String,
    val idle: String,
    val stopped: String,
    val messages: String,
    val yes: String,
    val no: String,
    val step: String,
    val dbMaintenanceStopWarning: String,
    val dbMaintenancePendingTemplate: String,
    val dbMaintenanceArchivePendingWarning: String,
    val dbMaintenanceConfirmTemplate: String,
    val operationCannotBeStopped: String,
    val interruptionDataLossRisk: String,
    val dbMaintenanceComplete: String,
    val dbMaintenanceFailed: String,
    val dbMaintenanceInterrupted: String,
    val dbMaintenanceAlreadyRunning: String,
    val dbMaintenanceCancelled: String,
    val dbMaintenanceGenericError: String,
    val dbMaintenanceArchivePath: String
)

fun strings(language: UiLanguage): UiStrings {
    return when (language) {
        UiLanguage.UK -> UiStrings(
            appSubtitle = "Прямий збір телеметрії • Sea Lion 07 EV",
            topBarSubtitle = "Збирання телеметрії авто",
            collection = "Збір",
            adb = "ADB",
            permissions = "Права",
            success = "Успіх",
            error = "Помилка",
            uk = "Укр",
            en = "Англ",
            dark = "Темна",
            light = "Світла",
            start = "Старт",
            stop = "Стоп",
            testConnection = "Тест зв'язку",
            autoStart = "Автоматичний запуск",
            controls = "Керування",
            mainTab = "Головна",
            allTab = "Всі дані",
            haTab = "HA інтеграція",
            storageTab = "Сховище",
            extraTab = "Налаштування",
            logsTab = "Логи",
            mainSubtitle = "Керування основним збором, швидка діагностика",
            allSubtitle = "Round-robin збір додаткових параметрів. Автоматичний запуск обмежений, щоб не вантажити систему.",
            haSubtitle = "MQTT для live state, InfluxDB для історії та Grafana. Канали незалежні.",
            storageSubtitle = "Архіви бази та ліміт зберігання",
            extraSubtitle = "Окремі налаштування (у стані тестування)",
            logsSubtitle = "Автооновлення вимкнене. Деталі читаються тільки після старту журналу.",
            dataCollection = "Збір даних",
            archiveDatabase = "Архівація бази",
            grantAdb = "Видати ADB",
            backgroundWork = "Робота у фоні",
            backgroundSetupTitle = "Робота у фоні",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Відкрийте DiLink settings і вимкніть примусове закриття застосунку у фоні.",
            backgroundSetupOpen = "Відкрити",
            backgroundSetupDismiss = "Зрозуміло",
            status = "Статус",
            activeChannels = "Активні канали",
            database = "База",
            activeDatabase = "Поточна база",
            archiveStorage = "Архіви",
            archiveStorageLimit = "Ліміт архівів, ГБ",
            archiveStorageLimitHint = "Автоматично видаляти найстаріші архіви після перевищення ліміту",
            archiveRoot = "Тека архівів",
            archiveCount = "Архівів",
            archiveStatusRaw = "raw",
            archiveStatusZip = "zip",
            archiveStatusTmp = "tmp",
            archiveStorageEmpty = "Архівів немає",
            archiveStorageRefresh = "Оновити сховище",
            archiveCalculating = "обчислюємо...",
            archiveSortNewestFirst = "Нові спочатку",
            archiveSortOldestFirst = "Старі спочатку",
            archiveCountShortTemplate = "(%d арх.)",
            deleteSelected = "Видалити вибране",
            selectedArchivesTemplate = "Вибрано: %d",
            deleteArchivesQuestion = "Видалити вибрані архіви?",
            deletingArchive = "Видаляємо архів...",
            size = "Розмір",
            megabytesUnit = "МБ",
            gigabytesUnit = "ГБ",
            rows = "Рядів",
            points = "точок",
            queued = "У черзі",
            exported = "Експортовано",
            currentVehicleState = "Поточний стан авто",
            kpiSoc = "SOC",
            kpiOdometer = "Пробіг",
            kpiCabinTemp = "Темп. салону",
            kpiSoh = "SOH",
            kpiCharging = "Заряджання",
            kpiDischarging = "Розряджання",
            kpiRange = "Запас ходу",
            kpiBatteryTemp = "Темп. батареї",
            kpiCellDelta = "Δ напруги комірки",
            parametersPerCycle = "Параметрів за цикл",
            battery = "Батарея",
            motion = "Рух",
            body = "Кузов",
            climate = "Клімат",
            safety = "Безпека",
            driverAssist = "Асистенти",
            sharedCategories = "Спільні категорії MQTT/InfluxDB",
            reExport = "Ре-експорт",
            reExportHint = "Експорт історії тільки нових категорій",
            host = "Хост",
            port = "Порт",
            username = "Користувач",
            password = "Пароль",
            databaseField = "База даних",
            measurement = "Вимірювання",
            clientId = "ID клієнта",
            topicPrefix = "Префікс топіків",
            discoveryPrefix = "Префікс discovery",
            mqttCategories = "Категорії MQTT",
            influxCategories = "Категорії InfluxDB",
            keepWifi = "Утримувати Wi-Fi",
            keepMobile = "Утримувати моб. зв'язок",
            keepBluetooth = "Утримувати Bluetooth",
            restoreCollector = "Відновлювати сервіс",
            activateTailscale = "Активувати Tailscale",
            activateTailscaleDescription = "Перевіряти наявність Tailscale та активувати VPN",
            keepAlive = "Підтримка роботи",
            appRuntime = "Робота застосунку",
            shutdown = "Виключити",
            shutdownDescription = "Завершити роботу застосунку до наступного відкриття",
            network = "Мережа",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Оновлення",
            checkUpdates = "Перевірити оновлення",
            checkUpdatesDescription = "Перевіряти наявність нової версії та пропонувати оновитись",
            checkingForUpdate = "Перевіряємо оновлення...",
            downloadingUpdate = "Завантажуємо оновлення...",
            latestVersion = "Це остання версія застосунку",
            currentVersion = "Поточна версія:",
            availableVersion = "Доступна версія:",
            update = "Оновити",
            close = "Закрити",
            updateError = "Помилка перевірки оновлення",
            updateNetworkUnavailable = "Немає з'єднання. Перевірте мережу або VPN.",
            updateDownloadFailed = "Не вдалося завантажити оновлення.",
            updateVerificationFailed = "Файл оновлення не пройшов перевірку.",
            updateInstallFailed = "Не вдалося відкрити встановлення оновлення.",
            updateGenericError = "Не вдалося перевірити або встановити оновлення.",
            startJournal = "Старт журналу",
            stopJournal = "Стоп журналу",
            startLogcat = "Старт logcat",
            stopLogcat = "Стоп logcat",
            mainPolling = "Збір основних даних",
            allParameters = "Всі дані",
            mqttPublish = "MQTT публікація",
            influxExport = "InfluxDB експорт",
            lastSuccess = "Останній успіх",
            lastError = "Остання помилка",
            sessionErrors = "Помилки сесії",
            batch = "Батч",
            waiting = "очікування",
            running = "працює",
            exporting = "експортує",
            successful = "успішно",
            missing = "відсутні",
            ok = "OK",
            cancel = "Скасувати",
            idle = "очікування",
            stopped = "зупинено",
            messages = "повідомлень",
            yes = "Так",
            no = "Ні",
            step = "Крок",
            dbMaintenanceStopWarning = "Буде тимчасово зупинено основний збір, всі дані, MQTT та InfluxDB.",
            dbMaintenancePendingTemplate = "У черзі: MQTT %d, InfluxDB %d.",
            dbMaintenanceArchivePendingWarning = "Архівація з активною чергою може залишити частину даних тільки в архіві.",
            dbMaintenanceConfirmTemplate = "Виконати операцію %s?",
            operationCannotBeStopped = "Після початку зупинити операцію із застосунку неможливо.",
            interruptionDataLossRisk = "Переривання процесу створює ризик втрати даних!",
            dbMaintenanceComplete = "Операцію завершено",
            dbMaintenanceFailed = "Операцію не виконано",
            dbMaintenanceInterrupted = "Операцію перервано до завершення.",
            dbMaintenanceAlreadyRunning = "Операція вже виконується.",
            dbMaintenanceCancelled = "Операцію скасовано.",
            dbMaintenanceGenericError = "Операцію не виконано. Деталі записані в логах.",
            dbMaintenanceArchivePath = "Архів:"
        )

        UiLanguage.EN -> UiStrings(
            appSubtitle = "Direct telemetry collection • Sea Lion 07 EV",
            topBarSubtitle = "Auto telemetry collection",
            collection = "Collection",
            adb = "ADB",
            permissions = "Permissions",
            success = "Success",
            error = "Error",
            uk = "UA",
            en = "ENG",
            dark = "Dark",
            light = "Light",
            start = "Start",
            stop = "Stop",
            testConnection = "Test connection",
            autoStart = "Automatic start",
            controls = "Controls",
            mainTab = "Main",
            allTab = "All data",
            haTab = "HA integration",
            storageTab = "Storage",
            extraTab = "Options",
            logsTab = "Logs",
            mainSubtitle = "Main collection controls, quick diagnostics",
            allSubtitle = "Round-robin collection of additional parameters. Autostart is limited to reduce load.",
            haSubtitle = "MQTT for live state, InfluxDB for history and Grafana. Channels are independent.",
            storageSubtitle = "Database archives and storage limit",
            extraSubtitle = "Separate settings (testing)",
            logsSubtitle = "Auto-refresh is off. Details are read only after log tracking starts.",
            dataCollection = "Data collection",
            archiveDatabase = "Database archive",
            grantAdb = "Grant ADB",
            backgroundWork = "Background apps",
            backgroundSetupTitle = "Background work",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Open DiLink settings and disable forced background app shutdown for this app.",
            backgroundSetupOpen = "Open settings",
            backgroundSetupDismiss = "Got it",
            status = "Status",
            activeChannels = "Active channels",
            database = "Database",
            activeDatabase = "Active database",
            archiveStorage = "Archives",
            archiveStorageLimit = "Archive limit, GB",
            archiveStorageLimitHint = "Delete oldest archives automatically after the limit is exceeded",
            archiveRoot = "Archive folder",
            archiveCount = "Archives",
            archiveStatusRaw = "raw",
            archiveStatusZip = "zip",
            archiveStatusTmp = "tmp",
            archiveStorageEmpty = "No archives",
            archiveStorageRefresh = "Refresh storage",
            archiveCalculating = "calculating...",
            archiveSortNewestFirst = "Newest first",
            archiveSortOldestFirst = "Oldest first",
            archiveCountShortTemplate = "(%d arch.)",
            deleteSelected = "Delete selected",
            selectedArchivesTemplate = "Selected: %d",
            deleteArchivesQuestion = "Delete selected archives?",
            deletingArchive = "Deleting archive...",
            size = "Size",
            megabytesUnit = "MB",
            gigabytesUnit = "GB",
            rows = "Rows",
            points = "points",
            queued = "Queued",
            exported = "Exported",
            currentVehicleState = "Current vehicle state",
            kpiSoc = "SOC",
            kpiOdometer = "Odometer",
            kpiCabinTemp = "Cabin temp",
            kpiSoh = "SOH",
            kpiCharging = "Charging",
            kpiDischarging = "Discharging",
            kpiRange = "Range",
            kpiBatteryTemp = "Battery temp",
            kpiCellDelta = "Cell voltage Δ",
            parametersPerCycle = "Parameters per cycle",
            battery = "Battery",
            motion = "Motion",
            body = "Body",
            climate = "Climate",
            safety = "Safety",
            driverAssist = "Driver assist",
            sharedCategories = "Shared MQTT/InfluxDB categories",
            reExport = "Re-export",
            reExportHint = "Export history for new categories only",
            host = "Host",
            port = "Port",
            username = "Username",
            password = "Password",
            databaseField = "Database",
            measurement = "Measurement",
            clientId = "Client ID",
            topicPrefix = "Topic prefix",
            discoveryPrefix = "Discovery prefix",
            mqttCategories = "MQTT categories",
            influxCategories = "InfluxDB categories",
            keepWifi = "Keep Wi-Fi",
            keepMobile = "Keep mobile data",
            keepBluetooth = "Keep Bluetooth",
            restoreCollector = "Restore service",
            activateTailscale = "Activate Tailscale",
            activateTailscaleDescription = "Check for Tailscale and activate VPN",
            keepAlive = "Keep alive",
            appRuntime = "App runtime",
            shutdown = "Shutdown",
            shutdownDescription = "Stop the app until it is opened again",
            network = "Network",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Updates",
            checkUpdates = "Check for updates",
            checkUpdatesDescription = "Check for new version and offer updating",
            checkingForUpdate = "Checking for update...",
            downloadingUpdate = "Downloading update...",
            latestVersion = "This is the latest app version",
            currentVersion = "Current version:",
            availableVersion = "Available version:",
            update = "Update",
            close = "Close",
            updateError = "Update check error",
            updateNetworkUnavailable = "No connection. Check the network or VPN.",
            updateDownloadFailed = "Could not download the update.",
            updateVerificationFailed = "The update file failed verification.",
            updateInstallFailed = "Could not open update installation.",
            updateGenericError = "Could not check or install the update.",
            startJournal = "Start journal",
            stopJournal = "Stop journal",
            startLogcat = "Start logcat",
            stopLogcat = "Stop logcat",
            mainPolling = "Main polling",
            allParameters = "All data",
            mqttPublish = "MQTT publish",
            influxExport = "InfluxDB export",
            lastSuccess = "Last success",
            lastError = "Last error",
            sessionErrors = "Session errors",
            batch = "Batch",
            waiting = "waiting",
            running = "running",
            exporting = "exporting",
            successful = "success",
            missing = "missing",
            ok = "OK",
            cancel = "Cancel",
            idle = "idle",
            stopped = "stopped",
            messages = "messages",
            yes = "Yes",
            no = "No",
            step = "Step",
            dbMaintenanceStopWarning = "Main collection, all data, MQTT, and InfluxDB will be temporarily stopped.",
            dbMaintenancePendingTemplate = "Queued: MQTT %d, InfluxDB %d.",
            dbMaintenanceArchivePendingWarning = "Archiving with an active queue can leave some data only inside the archive.",
            dbMaintenanceConfirmTemplate = "Run operation %s?",
            operationCannotBeStopped = "After the operation starts, it cannot be stopped from the app.",
            interruptionDataLossRisk = "Process interruption creates data corruption risk!",
            dbMaintenanceComplete = "Operation complete",
            dbMaintenanceFailed = "Operation failed",
            dbMaintenanceInterrupted = "The operation was interrupted before completion.",
            dbMaintenanceAlreadyRunning = "The operation is already running.",
            dbMaintenanceCancelled = "The operation was cancelled.",
            dbMaintenanceGenericError = "The operation failed. Details were written to logs.",
            dbMaintenanceArchivePath = "Archive:"
        )
    }
}
