package com.bydcollector.collector.ui.compose

enum class AppTab {
    MAIN,
    ALL_PARAMETERS,
    HA,
    EXTRA,
    LOGS
}

enum class UiLanguage {
    UK,
    EN
}

enum class StatusKind {
    OK,
    WARNING,
    WAITING,
    ERROR
}

data class TabText(
    val title: String,
    val subtitle: String
)

data class UiStrings(
    val appSubtitle: String,
    val topBarSubtitle: String,
    val collection: String,
    val adb: String,
    val permissions: String,
    val success: String,
    val error: String,
    val uk: String,
    val en: String,
    val dark: String,
    val light: String,
    val start: String,
    val stop: String,
    val testConnection: String,
    val autoStart: String,
    val controls: String,
    val mainTab: String,
    val allTab: String,
    val haTab: String,
    val extraTab: String,
    val logsTab: String,
    val mainSubtitle: String,
    val allSubtitle: String,
    val haSubtitle: String,
    val extraSubtitle: String,
    val logsSubtitle: String,
    val dataCollection: String,
    val grantAdb: String,
    val backgroundWork: String,
    val backgroundSetupTitle: String,
    val backgroundSetupMessage: String,
    val backgroundSetupBody: String,
    val backgroundSetupOpen: String,
    val backgroundSetupDismiss: String,
    val status: String,
    val activeChannels: String,
    val database: String,
    val size: String,
    val rows: String,
    val points: String,
    val queued: String,
    val exported: String,
    val currentVehicleState: String,
    val parametersPerCycle: String,
    val battery: String,
    val motion: String,
    val body: String,
    val climate: String,
    val safety: String,
    val driverAssist: String,
    val sharedCategories: String,
    val reExport: String,
    val reExportHint: String,
    val host: String,
    val port: String,
    val username: String,
    val password: String,
    val databaseField: String,
    val measurement: String,
    val clientId: String,
    val topicPrefix: String,
    val discoveryPrefix: String,
    val mqttCategories: String,
    val influxCategories: String,
    val keepWifi: String,
    val keepMobile: String,
    val keepBluetooth: String,
    val restoreCollector: String,
    val network: String,
    val bluetooth: String,
    val collector: String,
    val updates: String,
    val checkUpdates: String,
    val checkUpdatesDescription: String,
    val checkingForUpdate: String,
    val downloadingUpdate: String,
    val latestVersion: String,
    val currentVersion: String,
    val availableVersion: String,
    val update: String,
    val close: String,
    val updateError: String,
    val startJournal: String,
    val stopJournal: String,
    val startLogcat: String,
    val stopLogcat: String,
    val mainPolling: String,
    val allParameters: String,
    val mqttPublish: String,
    val influxExport: String,
    val lastSuccess: String,
    val lastError: String,
    val sessionErrors: String,
    val batch: String,
    val waiting: String,
    val running: String,
    val exporting: String,
    val successful: String,
    val missing: String,
    val ok: String,
    val idle: String,
    val messages: String
)

fun strings(language: UiLanguage): UiStrings {
    return when (language) {
        UiLanguage.UK -> UiStrings(
            appSubtitle = "Прямий збір телеметрії • Sea Lion 07 EV",
            topBarSubtitle = "Збирання телеметрії авто",
            collection = "Збір",
            adb = "ADB",
            permissions = "Права",
            success = "Успіх",
            error = "Помилка",
            uk = "Укр",
            en = "Англ",
            dark = "Темна",
            light = "Світла",
            start = "Старт",
            stop = "Стоп",
            testConnection = "Тест зв'язку",
            autoStart = "Автоматичний запуск",
            controls = "Керування",
            mainTab = "Головна",
            allTab = "Всі параметри",
            haTab = "HA інтеграція",
            extraTab = "Дод. опції",
            logsTab = "Логи",
            mainSubtitle = "Керування основним збором, швидка діагностика",
            allSubtitle = "Round-robin збір додаткових параметрів. Автоматичний запуск обмежений, щоб не вантажити систему.",
            haSubtitle = "MQTT для live state, InfluxDB для історії та Grafana. Канали незалежні.",
            extraSubtitle = "Окремі налаштування (у стані тестування)",
            logsSubtitle = "Автооновлення вимкнене. Деталі читаються тільки після старту журналу.",
            dataCollection = "Збір даних",
            grantAdb = "Видати ADB",
            backgroundWork = "Робота у фоні",
            backgroundSetupTitle = "Робота у фоні",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Відкрийте DiLink settings і вимкніть примусове закриття застосунку у фоні.",
            backgroundSetupOpen = "Відкрити",
            backgroundSetupDismiss = "Зрозуміло",
            status = "Статус",
            activeChannels = "Активні канали",
            database = "База",
            size = "Розмір",
            rows = "Рядів",
            points = "точок",
            queued = "У черзі",
            exported = "Експортовано",
            currentVehicleState = "Поточний стан авто",
            parametersPerCycle = "Параметрів за цикл",
            battery = "Батарея",
            motion = "Рух",
            body = "Кузов",
            climate = "Клімат",
            safety = "Безпека",
            driverAssist = "Асистенти",
            sharedCategories = "Спільні категорії MQTT/InfluxDB",
            reExport = "Ре-експорт",
            reExportHint = "Експорт історії тільки нових категорій",
            host = "Хост",
            port = "Порт",
            username = "Користувач",
            password = "Пароль",
            databaseField = "База даних",
            measurement = "Вимірювання",
            clientId = "ID клієнта",
            topicPrefix = "Префікс топіків",
            discoveryPrefix = "Префікс discovery",
            mqttCategories = "Категорії MQTT",
            influxCategories = "Категорії InfluxDB",
            keepWifi = "Утримувати Wi-Fi",
            keepMobile = "Утримувати моб. зв'язок",
            keepBluetooth = "Утримувати Bluetooth",
            restoreCollector = "Відновлювати сервіс",
            network = "Мережа",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Оновлення",
            checkUpdates = "Перевірити оновлення",
            checkUpdatesDescription = "Перевіряти наявність нової версії та пропонувати оновитись",
            checkingForUpdate = "Перевіряємо оновлення...",
            downloadingUpdate = "Завантажуємо оновлення...",
            latestVersion = "Це остання версія застосунку",
            currentVersion = "Поточна версія:",
            availableVersion = "Доступна версія:",
            update = "Оновити",
            close = "Закрити",
            updateError = "Помилка перевірки оновлення",
            startJournal = "Старт журналу",
            stopJournal = "Стоп журналу",
            startLogcat = "Старт logcat",
            stopLogcat = "Стоп logcat",
            mainPolling = "Збір основних даних",
            allParameters = "Всі параметри",
            mqttPublish = "MQTT публікація",
            influxExport = "InfluxDB експорт",
            lastSuccess = "Останній успіх",
            lastError = "Остання помилка",
            sessionErrors = "Помилки сесії",
            batch = "Батч",
            waiting = "очікування",
            running = "працює",
            exporting = "експортує",
            successful = "успішно",
            missing = "відсутні",
            ok = "OK",
            idle = "очікування",
            messages = "повідомлень"
        )

        UiLanguage.EN -> UiStrings(
            appSubtitle = "Direct telemetry collection • Sea Lion 07 EV",
            topBarSubtitle = "Auto telemetry collection",
            collection = "Collection",
            adb = "ADB",
            permissions = "Permissions",
            success = "Success",
            error = "Error",
            uk = "UA",
            en = "ENG",
            dark = "Dark",
            light = "Light",
            start = "Start",
            stop = "Stop",
            testConnection = "Test connection",
            autoStart = "Automatic start",
            controls = "Controls",
            mainTab = "Main",
            allTab = "All parameters",
            haTab = "HA integration",
            extraTab = "Extra options",
            logsTab = "Logs",
            mainSubtitle = "Main collection controls, quick diagnostics",
            allSubtitle = "Round-robin collection of additional parameters. Autostart is limited to reduce load.",
            haSubtitle = "MQTT for live state, InfluxDB for history and Grafana. Channels are independent.",
            extraSubtitle = "Separate settings (testing)",
            logsSubtitle = "Auto-refresh is off. Details are read only after log tracking starts.",
            dataCollection = "Data collection",
            grantAdb = "Grant ADB",
            backgroundWork = "Background apps",
            backgroundSetupTitle = "Background work",
            backgroundSetupMessage = "Set Disable background Apps -> BYD Collector = OFF",
            backgroundSetupBody = "Open DiLink settings and disable forced background app shutdown for this app.",
            backgroundSetupOpen = "Open settings",
            backgroundSetupDismiss = "Got it",
            status = "Status",
            activeChannels = "Active channels",
            database = "Database",
            size = "Size",
            rows = "Rows",
            points = "points",
            queued = "Queued",
            exported = "Exported",
            currentVehicleState = "Current vehicle state",
            parametersPerCycle = "Parameters per cycle",
            battery = "Battery",
            motion = "Motion",
            body = "Body",
            climate = "Climate",
            safety = "Safety",
            driverAssist = "Driver assist",
            sharedCategories = "Shared MQTT/InfluxDB categories",
            reExport = "Re-export",
            reExportHint = "Export history for new categories only",
            host = "Host",
            port = "Port",
            username = "Username",
            password = "Password",
            databaseField = "Database",
            measurement = "Measurement",
            clientId = "Client ID",
            topicPrefix = "Topic prefix",
            discoveryPrefix = "Discovery prefix",
            mqttCategories = "MQTT categories",
            influxCategories = "InfluxDB categories",
            keepWifi = "Keep Wi-Fi",
            keepMobile = "Keep mobile data",
            keepBluetooth = "Keep Bluetooth",
            restoreCollector = "Restore service",
            network = "Network",
            bluetooth = "Bluetooth",
            collector = "Collector",
            updates = "Updates",
            checkUpdates = "Check for updates",
            checkUpdatesDescription = "Check for new version and offer updating",
            checkingForUpdate = "Checking for update...",
            downloadingUpdate = "Downloading update...",
            latestVersion = "This is the latest app version",
            currentVersion = "Current version:",
            availableVersion = "Available version:",
            update = "Update",
            close = "Close",
            updateError = "Update check error",
            startJournal = "Start journal",
            stopJournal = "Stop journal",
            startLogcat = "Start logcat",
            stopLogcat = "Stop logcat",
            mainPolling = "Main polling",
            allParameters = "All parameters",
            mqttPublish = "MQTT publish",
            influxExport = "InfluxDB export",
            lastSuccess = "Last success",
            lastError = "Last error",
            sessionErrors = "Session errors",
            batch = "Batch",
            waiting = "waiting",
            running = "running",
            exporting = "exporting",
            successful = "success",
            missing = "missing",
            ok = "OK",
            idle = "idle",
            messages = "messages"
        )
    }
}
